config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/pki-validation/godaddy.html', to: 'home#godaddy', as: :godaddy
  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/usuarios', to: 'dashboard#usuarios', as: :dashboard_usuarios
  get 'dashboard/carrinhos', to: 'dashboard#carrinhos', as: :dashboard_carrinhos
  get 'dashboard/vendas', to: 'dashboard#vendas', as: :dashboard_vendas
  get 'order/new', to: 'order#new', as: :new_order
  post 'order/frete', to: 'order#frete', as: :frete

  resources :order
  get 'galeria/index'

  post 'contato', to: 'home#create', as: :contatos
  post 'oferta', to: 'home#create_oferta', as: :ofertas

  post ':user_name/pedidos', to: 'pedidos#create', as: :pedidos_create
  get ':user_name/pedidos', to: 'pedidos#index', as: :pedidos
  get ':user_name/pedidos/:id', to: 'pedidos#show', as: :pedido
  delete ':user_name/pedidos/:id/destroy', to: 'pedidos#destroy', as: :pedido_destroy
  delete ':user_name/pedidos/destroy_all', to: 'pedidos#destroy_all', as: :pedido_destroy_all
  post '/pedidos/:id/ped_comments', to: 'ped_comments#create', as: :pedido_ped_comments
  delete'/pedidos/:id/ped_comments/:ped_id', to: 'ped_comments#destroy', as: :pedido_ped_comment

  get '/tutorial', to: 'learn#index', as: :learn
  get '/tutorial/acabamento', to: 'learn#acabamento', as: :learn_acabamento
  get '/tutorial/modelagem', to: 'learn#modelagem', as: :learn_modelagem
  get '/tutorial/material', to: 'learn#material', as: :learn_material
  get '/tutorial/primeira_impressao', to: 'learn#primeira', as: :learn_primeira

  post '/checkouts', to: 'ckeckout#checkouts', as: :checkouts_show
  post '/order/notification', to: 'order#notification', as: :notification_order
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'printers', to: 'printers#index', as: :printers
  get 'printers/new', to: 'printers#new', as: :new_printer
  get 'printers/:id/active', to: 'printers#active', as: :active_printer
  get 'printers/:id/deactive', to: 'printers#deactive', as: :deactive_printer
  resources :printers

  get 'galeria', to: 'galeria#index', as: :galeria
  get 'galeria/arte', to: 'galeria#Arte', as: :galeria_arte
  get 'galeria/fashion', to: 'galeria#Fashion', as: :galeria_fashion
  get 'galeria/gadgets', to: 'galeria#Gadgets', as: :galeria_gadgets
  get 'galeria/hobby', to: 'galeria#Hobby', as: :galeria_hobby
  get 'galeria/casa', to: 'galeria#Casa', as: :galeria_casa
  get 'galeria/aprendizado', to: 'galeria#Aprendizado', as: :galeria_aprendizado
  get 'galeria/modelos', to: 'galeria#Modelos', as: :galeria_modelos
  get 'galeria/ferramentas', to: 'galeria#Ferramentas', as: :galeria_ferramentas
  get 'galeria/Brinquedos', to: 'galeria#Brinquedos', as: :galeria_brinquedos
  get 'galeria/outros', to: 'galeria#Outros', as: :galeria_outros


  get 'browse', to: 'posts#browse', as: :browse_posts

  get 'home/index'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  post '/carrinho/create', to: 'carrinho#create', as: :create_carrinho
  post '/carrinho/:carrinho_id/car_comments', to: 'car_comments#create', as: :carrinho_car_comments
  delete '/carrinho/:carrinho_id/car_comments/:id', to: 'car_comments#destroy', as: :carrinho_car_comment
  get 'posts', to: 'posts#index', as: :posts
  get "/users/auth/facebook" => "callbacks#facebook", as: :facebook
  get 'profiles/show'
  resources :posts do
    collection do
      get :autocomplete
      get :autocomplete2
      get :autocompletepre
      get :autocompletepre2
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }
  root 'home#index'
  get '/search', to: 'home#search', as: :search
  get '/importar', to: 'posts#importar', as: :importar
  post '/importar/create', to: 'posts#importar_create', as: :importar_create

  get '/:user_name', to: 'profiles#show', as: :profile
  get '/:user_name/conta_bancaria', to: 'profiles#banco', as: :banco
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get ':user_name/printers', to: 'profiles#printers', as: :printers_profile
  get ':user_name/destaques', to:'profiles#destaques', as: :destaques_profile
  get ':user_name/projetos', to:'profiles#projetos', as: :projetos_profile
  get ':user_name/seguidores', to:'profiles#seguidores', as: :seguidores_profile
  get ':user_name/seguindo', to:'profiles#seguindo', as: :seguindo_profile
  get ':user_name/carrinho', to:'order#new', as: :carrinho
  get ':user_name/carrinhos', to:'carrinhos#index', as: :carrinhos
  get ':user_name/carrinho_feito/:id', to: 'carrinhos#show', as: :carrinho_feito
  post ':user_name/order/create', to:'order#create', as: :order_create
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  #post 'pedidos/create', to: 'pedidos#create', as: :pedidos
  post 'posts/:id/checkout', to: 'ckeckout#create', as: :checkout
  get 'posts/:id/new', to: 'ckeckout#new', as: :new_checkout
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user
	layout :false
	def index
		@sidenav = 'dashboard'

	end
	def usuarios
		@users = User.all.order('created_at DESC')
		@sidenav = 'usuarios'

	end
	def carrinhos
		@carrinhos = Carrinho.all.order('created_at DESC')
		@sidenav = 'carrinhos'

	end
	def vendas
		@vendas = Carrinho.where(status: 'Pago')
		@sidenav = 'vendas'
		@receita = 0
		@vendas.each do |venda|
			if @venda
				@receita = @receita + venda.price
			end
		end

	end


	private
	def set_user
		if current_user.tipo != 'admin'
			redirect_to galeria_path
		end
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_navs.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="images/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <%=render 'javas'%>
	<title>Dashboard - Beeprinted</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <%= stylesheet_link_tag "bootstrap.min"%>

    <!-- Animation library for notifications   -->
    <%= stylesheet_link_tag "animate"%>
    <!--<link href="assets/css/animate.min.css" rel="stylesheet"/>-->

    <!--  Light Bootstrap Table core CSS    -->
    <%= stylesheet_link_tag "light-bootstrap-dashboard"%>
    <!--<link href="assets/css/light-bootstrap-dashboard.css" rel="stylesheet"/>-->


    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "pe-icon-7-stroke"%>

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="../images/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="<%=root_path%>" class="simple-text">
                    BEEPRINTED
                </a>
            </div>

            <ul class="nav">
                <%if @sidenav == 'dashboard'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href=<%=dashboard_path%> id='dashboard'>
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <%if @sidenav == 'usuarios'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href=<%=dashboard_usuarios_path%> id='usuarios'>
                        <i class="pe-7s-user"></i>
                        <p>Usuários</p>
                    </a>
                </li>
                <%if @sidenav == 'carrinhos'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href=<%=dashboard_carrinhos_path%> id='carrinhos'>
                        <i class="pe-7s-cart"></i>
                        <p>Carrinhos</p>
                    </a>
                </li>
                <%if @sidenav == 'vendas'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href=<%=dashboard_vendas_path%> id='vendas'>
                        <i class="pe-7s-note2"></i>
                        <p>Controle de Vendas</p>
                    </a>
                </li>
                <%if @sidenav == 'mapa'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href="maps.html" id='mapa'>
                        <i class="pe-7s-map-marker"></i>
                        <p>Mapa de Usuários</p>
                    </a>
                </li>
                <%if @sidenav == 'notificacoes'%>
                <li class="active">
                <%else%>
                <li>
                <%end%>
                    <a href="notifications.html" id='notificacoes'>
                        <i class="pe-7s-bell"></i>
                        <p>Notificações</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
								<p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-sm hidden-xs"></b>
                                    <span class="notification hidden-sm hidden-xs">5</span>
									<p class="hidden-lg hidden-md">
										5 Notifications
										<b class="caret"></b>
									</p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>
                        <li>
                           <a href="">
                                <i class="fa fa-search"></i>
								<p class="hidden-lg hidden-md">Search</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href="">
                               <p>Account</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
										Dropdown
										<b class="caret"></b>
									</p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                        </li>
                        <li>
                            <a href="#">
                                <p>Log out</p>
                            </a>
                        </li>
						<li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

app/views/dashboard/carrinhos.html.erb
 <%= render 'dashboard/navs'%>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Carrinhos (<%=@carrinhos.count%>)</h4>
                                <p class="category">Encontre aqui as principais informações</p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover" style="margin-bottom:0px">
                                    <thead>
                                        <th>ID</th>
                                    	<th>Nome Usuário</th>
                                    	<th>Status</th>
                                    	<th>Orders</th>
                                        <th>Preço</th>
                                        <th>Frete</th>

                                    </thead>
                                    <tbody>
                                    <% @carrinhos.each_with_index  do |carrinho,index|%>
                                        <tr onclick='show_details("<%=index%>")'>
                                        	<td>
                                             <%=carrinho.id%>
                                                
                                            </td>
                                        	<td>
                                            <a href=<%= profile_path(carrinho.user.user_name)%>><%=carrinho.user.completo%></a>
                                                
                                            </td>

                                        	<td><%=carrinho.status%></td>
                                            <td><%=carrinho.orders.count%></td>
                                            <td><%=carrinho.price%></td>
                                            <td></td>
                                            </tr>
                                            <tr>
                                            <div>
                                            <!--<table class="table table-hover" style="margin-bottom:0px; background-color:#eeeeee">-->
                                                <thead id="head_<%=index%>" style='background-color:#eeeeee;display:none;'>
                                                    <th>Order</th>
                                                    <th>Post Nome</th>
                                                    <th>Post ID</th>
                                                    <th>Peso</th>
                                                    <th>Quantidade</th>
                                                    <th>Preço</th>
                                                </thead>
                                                <tbody id="body_<%=index%>"  style='background-color:#dddddd;display:none;'>
                                                    <% carrinho.orders.each do |order|%>
                                                    <tr style='background-color:#dddddd'>
                                                        <td>
                                                            <%=order.id%>
                                                        </td>
                                                        <td>
                                                            <%=order.post.caption%>
                                                        </td>
                                                        <td>
                                                            <%=order.post.id%>
                                                        </td>
                                                        
                                                        <td>
                                                            <%=order.peso%> g
                                                        </td>
                                                        <td>
                                                            <%=order.quantidade%>
                                                        </td>
                                                        <td>
                                                            R$<%=order.price%>
                                                        </td>
                                                    </tr>
                                                    <%end%>
                                                </tbody>
                                            </div>
                                            <!--</table>-->
                                            </tr>
                                    <%end%>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>




                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href=<%=root_path%>>BeePrinted</a>, Imprima em Comunidade
                </p>
            </div>
        </footer>


    </div>
</div>


</body>
<script>
function show_details(n){
    var x = document.getElementById("head_"+n);
    if(x.style.display === 'none'){
        $("#head_"+n).show();
        $("#body_"+n).show(); 
    } 
    else{
        $("#head_"+n).hide();
        $("#body_"+n).hide();
    }
    console.log("head_"+n);

}
</script>

app/views/dashboard/usuarios.html.erb
 <%= render 'dashboard/navs'%>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Usuários (<%= @users.count%>)</h4>
                                <p class="category">Encontre aqui as principais informações</p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped" style="margin-bottom:0px">
                                    <thead>
                                        <th>ID</th>
                                    	<th>Nome</th>
                                    	<th>Email</th>
                                    	<th>Projetos</th>
                                    	<th>Carrinhos</th>
                                        <th>Compras</th>
                                    </thead>
                                    <tbody>
                                    <% @users.each do |user|%>
                                        <tr>
                                        	<td>
                                             <%=user.id%>
                                                
                                            </td>
                                        	<td>
                                            <a href=<%= profile_path(user.user_name)%>><%=user.completo%></a>
                                                
                                            </td>

                                        	<td><%=user.email%></td>
                                            <td><%=user.posts.count%></td>
                                        	<td><%=user.carrinhos.count%></td>
                                        	<td><%=user.carrinhos.where(status: 'Pago').count%></td>

                                        </tr>
                                    <%end%>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>




                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href=<%=root_path%>>BeePrinted</a>, Imprima em Comunidade
                </p>
            </div>
        </footer>


    </div>
</div>


</body>

app/views/dashboard/vendas.html.erb
 <%= render 'dashboard/navs'%>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                <h4 class="title" style='padding-left:20px'>Receita: R$<%='%.2f' % @receita.round(2)%></h4>
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Vendas (<%= @vendas.count%>)</h4>
                                <p class="category">Encontre aqui as principais informações</p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped" style="margin-bottom:0px">
                                    <thead>
                                        <th>Carrinho ID</th>
                                    	<th>Nome do Usuário</th>
                                    	<th>Email</th>
                                    	<th>Carrinho Id</th>
                                    	<th>Preço</th>
                                        <th>Status</th>
                                    </thead>
                                    <tbody>
                                    <% @vendas.each do |venda|%>
                                        <tr>
                                        	<td>
                                             <%=venda.id%>
                                                
                                            </td>
                                        	<td>
                                            <a href=<%= profile_path(venda.user.user_name)%>><%=venda.user.completo%></a>
                                                
                                            </td>

                                        	<td><%=venda.user.email%></td>
                                            <td><%=venda.id%></td>
                                        	<td><%=venda.price%></td>
                                        	<td><%=venda.status%></td>

                                        </tr>
                                    <%end%>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>




                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href=<%=root_path%>>BeePrinted</a>, Imprima em Comunidade
                </p>
            </div>
        </footer>


    </div>
</div>


</body>