config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/pki-validation/godaddy.html', to: 'home#godaddy', as: :godaddy
  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/usuarios', to: 'dashboard#usuarios', as: :dashboard_usuarios
  get 'dashboard/carrinhos', to: 'dashboard#carrinhos', as: :dashboard_carrinhos
  get 'dashboard/vendas', to: 'dashboard#vendas', as: :dashboard_vendas
  get 'order/new', to: 'order#new', as: :new_order
  post 'order/frete', to: 'order#frete', as: :frete

  resources :order
  get 'galeria/index'

  post 'contato', to: 'home#create', as: :contatos
  post 'oferta', to: 'home#create_oferta', as: :ofertas

  post ':user_name/pedidos', to: 'pedidos#create', as: :pedidos_create
  get ':user_name/pedidos', to: 'pedidos#index', as: :pedidos
  get ':user_name/pedidos/:id', to: 'pedidos#show', as: :pedido
  delete ':user_name/pedidos/:id/destroy', to: 'pedidos#destroy', as: :pedido_destroy
  delete ':user_name/pedidos/destroy_all', to: 'pedidos#destroy_all', as: :pedido_destroy_all
  post '/pedidos/:id/ped_comments', to: 'ped_comments#create', as: :pedido_ped_comments
  delete'/pedidos/:id/ped_comments/:ped_id', to: 'ped_comments#destroy', as: :pedido_ped_comment

  get '/tutorial', to: 'learn#index', as: :learn
  get '/tutorial/acabamento', to: 'learn#acabamento', as: :learn_acabamento
  get '/tutorial/modelagem', to: 'learn#modelagem', as: :learn_modelagem
  get '/tutorial/material', to: 'learn#material', as: :learn_material
  get '/tutorial/primeira_impressao', to: 'learn#primeira', as: :learn_primeira

  post '/checkouts', to: 'ckeckout#checkouts', as: :checkouts_show
  post '/order/notification', to: 'order#notification', as: :notification_order
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'printers', to: 'printers#index', as: :printers
  get 'printers/new', to: 'printers#new', as: :new_printer
  get 'printers/:id/active', to: 'printers#active', as: :active_printer
  get 'printers/:id/deactive', to: 'printers#deactive', as: :deactive_printer
  resources :printers

  get 'galeria', to: 'galeria#index', as: :galeria
  get 'galeria/arte', to: 'galeria#Arte', as: :galeria_arte
  get 'galeria/fashion', to: 'galeria#Fashion', as: :galeria_fashion
  get 'galeria/gadgets', to: 'galeria#Gadgets', as: :galeria_gadgets
  get 'galeria/hobby', to: 'galeria#Hobby', as: :galeria_hobby
  get 'galeria/casa', to: 'galeria#Casa', as: :galeria_casa
  get 'galeria/aprendizado', to: 'galeria#Aprendizado', as: :galeria_aprendizado
  get 'galeria/modelos', to: 'galeria#Modelos', as: :galeria_modelos
  get 'galeria/ferramentas', to: 'galeria#Ferramentas', as: :galeria_ferramentas
  get 'galeria/Brinquedos', to: 'galeria#Brinquedos', as: :galeria_brinquedos
  get 'galeria/outros', to: 'galeria#Outros', as: :galeria_outros


  get 'browse', to: 'posts#browse', as: :browse_posts

  get 'home/index'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  post '/carrinho/create', to: 'carrinho#create', as: :create_carrinho
  post '/carrinho/:carrinho_id/car_comments', to: 'car_comments#create', as: :carrinho_car_comments
  delete '/carrinho/:carrinho_id/car_comments/:id', to: 'car_comments#destroy', as: :carrinho_car_comment
  get 'posts', to: 'posts#index', as: :posts
  get "/users/auth/facebook" => "callbacks#facebook", as: :facebook
  get 'profiles/show'
  resources :posts do
    collection do
      get :autocomplete
      get :autocomplete2
      get :autocompletepre
      get :autocompletepre2
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }
  root 'home#index'
  get '/search', to: 'home#search', as: :search
  get '/importar', to: 'posts#importar', as: :importar
  post '/importar/create', to: 'posts#importar_create', as: :importar_create

  get '/:user_name', to: 'profiles#show', as: :profile
  get '/:user_name/conta_bancaria', to: 'profiles#banco', as: :banco
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get ':user_name/printers', to: 'profiles#printers', as: :printers_profile
  get ':user_name/destaques', to:'profiles#destaques', as: :destaques_profile
  get ':user_name/projetos', to:'profiles#projetos', as: :projetos_profile
  get ':user_name/seguidores', to:'profiles#seguidores', as: :seguidores_profile
  get ':user_name/seguindo', to:'profiles#seguindo', as: :seguindo_profile
  get ':user_name/carrinho', to:'order#new', as: :carrinho
  get ':user_name/carrinhos', to:'carrinhos#index', as: :carrinhos
  get ':user_name/carrinho_feito/:id', to: 'carrinhos#show', as: :carrinho_feito
  post ':user_name/order/create', to:'order#create', as: :order_create
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  #post 'pedidos/create', to: 'pedidos#create', as: :pedidos
  post 'posts/:id/checkout', to: 'ckeckout#create', as: :checkout
  get 'posts/:id/new', to: 'ckeckout#new', as: :new_checkout
end

app/models/carrinho.rb
class Carrinho < ActiveRecord::Base
	belongs_to :user
	has_many :orders, dependent: :destroy
	has_many :car_comments, dependent: :destroy
end

app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
	before_action :set_user
	def index
		@carrinhos = @user.carrinhos.where.not(status: 'criado').order('created_at DESC')
		if params[:identifier]
			@carrinho = @user.carrinhos.find(params[:identifier])
		else
			@carrinho = @user.carrinhos.where.not(status: 'criado').last
		end
	end
	def show
		@carrinho = @user.carrinhos.find(params[:id])
		respond_to do |format|
        	format.html
        	format.js
        end
	end



	private
	def set_user
		@user = User.find_by(user_name: params[:user_name])
		if (@user != current_user)
			if(current_user.tipo!='admin')
				redirect_to galeria_path
			end
		end
	end
end

app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

app/views/carrinhos/_carrinho.html.erb
      <div id="comments">
          <%= render carrinho.car_comments, carrinho: carrinho %>

      </div>
  <% if carrinho.user == current_user %>
    <div class="w3-row-padding w3-section " style="padding-top:25px; border-top:1px solid #eeeeee">
      <div class="w3-col s2" style="width:12%">
        <%= image_tag current_user.avatar.url(:medium),class: "w3-circle", style: 'height:50px;width:50px' %>
      </div>
      <div class="w3-col s8" style="background-color:#eeeeee; border-radius:10px;padding:10px">
      <%= form_for([carrinho, carrinho.car_comments.new], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Descreva aqui como é o seu projeto...', style: "width:100%;background-color:#eeeeee;border:none;size:30", id: 'comment_content_form' %>
        <% end %>
      </div>
    </div>

  <% else %>
  <div class="w3-row-padding w3-section " style="padding-top:25px; border-top:1px solid #eeeeee">
      <div class="w3-col s2 w3-right" style="width:12%">
        <%= image_tag "logo.jpg",class: "w3-circle w3-right", style: 'height:50px;width:50px' %>
      </div>
      <div class="w3-col s8 w3-right" style="background-color:#eeeeee; border-radius:10px;padding:10px">
      <%= form_for([carrinho, carrinho.car_comments.new], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Descreva aqui como é o seu projeto...', style: "width:100%;background-color:#eeeeee;border:none;size:30", id: 'comment_content_form' %>
        <% end %>
      </div>
    </div>
  <%end%>

app/views/carrinhos/_principal.html.erb
<div class="w3-container" id="apartment">
    <h2 class="w3-text-green">Seu Carrinho</h2>

    <% carrinho.orders.each do |order| %>
      <div class="w3-display-container mySlides">
      <%= link_to (image_tag order.post.image.url(:medium), style:"width:100%;margin-bottom:-6px"), post_path(order.post) %>
        <div class="w3-display-bottomleft w3-container w3-black">
          <% if order.quantidade == 1%>
            <p><%= order.post.caption %></p>
          <% else %>
            <p><%= order.post.caption %> <strong>x<%=order.quantidade%></strong></p>
          <% end %>
        </div>
        <%= link_to order_path(id: order, user_name: carrinho.user.user_name), method: :delete, data: { confirm: "Are you sure?" } do %>
        <div class="w3-display-topright w3-container w3-black">
          <span class="fa fa-remove delete-comment" style="color:gray; font-size:20px"></span>
        </div>
      <% end %>  
      </div>
    <% end %>


  </div>
  <% if carrinho.orders.count > 1 %>
  <% carrinho.orders.in_groups_of(4, false).each_with_index do |group,index1| %>
  <div class="w3-row-padding w3-section">
  <% group.each_with_index do |order, index2| %>
    <div class="w3-col s3">
      <%=image_tag order.post.image.url(:medium),style:"width:100%; cursor:pointer", onclick:"currentDiv(#{(index1*4) + index2+1})",class:"demo w3-opacity w3-hover-opacity-off", title: order.post.caption%>
    </div>
  <% end %>
  </div>
  <% end %>
  <% end %>
  <script>
// Slideshow Apartment Images
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
     dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-opacity-off";
}
</script>

app/views/carrinhos/index.html.erb
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Open Sans", sans-serif}
.mySlides {display:none}
</style>
<body class="w3-content" style="max-width:1100px">

<!-- Sidenav/menu -->
<br>
<br>
<nav class="w3-sidenav w3-light-grey w3-collapse w3-top w3-border-left" style="z-index:3;width:260px; overflow: visible;" id="mySidenav">
<br>
<br>
<br>
  <div class="w3-container w3-padding-8">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-closebtn w3-hover-text-red"></i>
    <p style="font-weight:bold;color:#666; border-bottom: 2px solid #ccc;font-size:25px;margin:0px;"> Suas Compras </p>
    <p style="font-style:italic;color:#666;font-size:13px;text-align: justify;">Encontre aqui todos os seus carrinhos que passaram ou estão passando pelo processo de pagamento</p>
        <%if @carrinhos.any? %>
          <br>
          <% @carrinhos.each do |carrinho|%>
            <a href=<%=carrinho_feito_path(@user.user_name,carrinho)%> class="media list-group-item lista_carrinhos carrinho_<%=carrinho.id%>" data-remote="true" id="carrinho_<%=carrinho.id%>">
              <span class="pull-left">
               <%= image_tag carrinho.orders.first.post.image.url(:medium), class: "media-object img-circle img-notification"%>
              </span>
              <span id="content_<%carrinho.id%>" class="media-body">
              <%if carrinho.orders.count != 1%>
              	<p style='margin-bottom:0px;'><%=carrinho.orders.count%> Modelos</p>
              <%else%>
              	<p style='margin-bottom:0px;'><%=carrinho.orders.count%> Modelo</p>
              <%end%>
              <small class="text-muted">
              	<p><%=carrinho.status%></p>
              </small>
              <small class="text-muted">
                <%= time_ago_in_words carrinho.created_at%>
               </small>
              </span>
            </a>
          <% end %>
          <% end %>
    
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-black w3-xlarge w3-padding-80">
  <span class="w3-left">Pedidos</span>
  <a href="javascript:void(0)" class="w3-right w3-opennav" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidenav on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-white w3-border-right" style="margin-left:260px;">
<div style="overflow:auto;">
  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:80px"></div>


  <%if @carrinhos.any? %>
<bla id='order_foto'>
    <% if @carrinho.orders.any? %>
    <div id='fotos_carrinho'>
      <%= render 'carrinhos/principal', carrinho: @carrinho %>
    </div>
    <% else %>
      <h3>Você nao possui nenhum pedido. Visite nossa galeria</h3>
      <p class='w3-center btn'><%=link_to 'Galeria', galeria_path%></p>
    <% end %>
  </bla>
  <hr style="margin-bottom:2px; border-top: 1px solid #dddddd">
  <div class='w3-container' style="color:#999999">Para cancelar algum pedido, clique no "x" no topo esquerdo da respectiva foto</div>
  <!-- Slideshow Header -->

  <!-- Contact -->
  <div class="w3-container" id="contact" style="margin-top:15px; border-top: 2px solid #eeeeee">
    <div class="post-bottom">
    <div class="w3-row-padding w3-section" style="padding-top:25px; border-top:1px solid #eeeeee">
            <div class="w3-col s2 w3-right" style="width:12%">
              <%= image_tag "logo.jpg",class: "w3-circle w3-right", style: 'height:50px;width:50px' %>
            </div>
              <div class="w3-col s8 w3-right" style="background-color:#eeeeee; border-radius:10px;padding:10px">
                Olá :)
            </div>
    </div>
    <div class="w3-row-padding w3-section" style="padding-top:25px; border-top:1px solid #eeeeee">
            <div class="w3-col s2 w3-right" style="width:12%">
              <%= image_tag "logo.jpg",class: "w3-circle w3-right", style: 'height:50px;width:50px' %>
            </div>
              <div class="w3-col s8 w3-right" style="background-color:#eeeeee; border-radius:10px;padding:10px">
                Por favor, descreva aqui suas dúvidas sobre o processo de pagamento, modelagem, entrega ou sobre outras informaçoes relacionadas ao seu carrinho...
            </div>
    </div>
    <div id='carrinho'>
      <%= render 'carrinho', carrinho: @carrinho %>
    </div>
    <%else%>
    <br>
    <br>
    <h2 class='w3-center'>Você ainda nao possui pedidos!</h2>
    <%end%>
  </div>
<div class="w3-container" style="border-top:2px solid #eeeeee;margin-top:15px;padding-top:15px;">
  <div class="w3-center">
  Pagamento Seguro por
  </div>
  <div class="w3-center">
   <img src="https://stc.pagseguro.uol.com.br/public/img/banners/pagamento/todos_estatico_550_100.gif" alt="Logotipos de meios de pagamento do PagSeguro" title="Este site aceita pagamentos com Visa, Mastercard, Diners, American Express, Hipercard, Aura, Elo, PLENOCard, PersonalCard, BrasilCard, FORTBRASIL, Cabal, Mais!, Avista, Grandcard, Sorocred, Bradesco, Itaú, Banco do Brasil, Banrisul, Banco HSBC, saldo em conta PagSeguro e boleto.">
</div>
  <footer class="w3-container w3-padding-16" style="margin-top:32px">Powered by <a href=<%=root_path%> title="BEEPRINTED" target="_blank" class="w3-hover-text-green">BEEPRINTED</a></footer>
</div>
</div>


<!-- End page content -->
</div>
<!-- Subscribe Modal -->
<script>
$(".lista_carrinhos").css('background-color', 'white');
$("#carrinho_<%=@carrinho.id%>").css('background-color', '#dddddd');
</script>
<script>
// Script to open and close sidenav when on tablets and phones
function w3_open() {
    document.getElementById("mySidenav").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
    document.getElementById("mySidenav").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}

</body>

app/views/carrinhos/show.js.erb
$("#carrinho").html("<%=j render 'carrinho', carrinho: @carrinho %>");
$(".lista_carrinhos").css('background-color', 'white');
$("#carrinho_<%=@carrinho.id%>").css('background-color', '#dddddd');
$("#fotos_carrinho").html("<%=j render 'carrinhos/principal', carrinho: @carrinho %>");