config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/pki-validation/godaddy.html', to: 'home#godaddy', as: :godaddy
  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/usuarios', to: 'dashboard#usuarios', as: :dashboard_usuarios
  get 'dashboard/carrinhos', to: 'dashboard#carrinhos', as: :dashboard_carrinhos
  get 'dashboard/vendas', to: 'dashboard#vendas', as: :dashboard_vendas
  get 'order/new', to: 'order#new', as: :new_order
  post 'order/frete', to: 'order#frete', as: :frete

  resources :order
  get 'galeria/index'

  post 'contato', to: 'home#create', as: :contatos
  post 'oferta', to: 'home#create_oferta', as: :ofertas

  post ':user_name/pedidos', to: 'pedidos#create', as: :pedidos_create
  get ':user_name/pedidos', to: 'pedidos#index', as: :pedidos
  get ':user_name/pedidos/:id', to: 'pedidos#show', as: :pedido
  delete ':user_name/pedidos/:id/destroy', to: 'pedidos#destroy', as: :pedido_destroy
  delete ':user_name/pedidos/destroy_all', to: 'pedidos#destroy_all', as: :pedido_destroy_all
  post '/pedidos/:id/ped_comments', to: 'ped_comments#create', as: :pedido_ped_comments
  delete'/pedidos/:id/ped_comments/:ped_id', to: 'ped_comments#destroy', as: :pedido_ped_comment

  get '/tutorial', to: 'learn#index', as: :learn
  get '/tutorial/acabamento', to: 'learn#acabamento', as: :learn_acabamento
  get '/tutorial/modelagem', to: 'learn#modelagem', as: :learn_modelagem
  get '/tutorial/material', to: 'learn#material', as: :learn_material
  get '/tutorial/primeira_impressao', to: 'learn#primeira', as: :learn_primeira

  post '/checkouts', to: 'ckeckout#checkouts', as: :checkouts_show
  post '/order/notification', to: 'order#notification', as: :notification_order
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'printers', to: 'printers#index', as: :printers
  get 'printers/new', to: 'printers#new', as: :new_printer
  get 'printers/:id/active', to: 'printers#active', as: :active_printer
  get 'printers/:id/deactive', to: 'printers#deactive', as: :deactive_printer
  resources :printers

  get 'galeria', to: 'galeria#index', as: :galeria
  get 'galeria/arte', to: 'galeria#Arte', as: :galeria_arte
  get 'galeria/fashion', to: 'galeria#Fashion', as: :galeria_fashion
  get 'galeria/gadgets', to: 'galeria#Gadgets', as: :galeria_gadgets
  get 'galeria/hobby', to: 'galeria#Hobby', as: :galeria_hobby
  get 'galeria/casa', to: 'galeria#Casa', as: :galeria_casa
  get 'galeria/aprendizado', to: 'galeria#Aprendizado', as: :galeria_aprendizado
  get 'galeria/modelos', to: 'galeria#Modelos', as: :galeria_modelos
  get 'galeria/ferramentas', to: 'galeria#Ferramentas', as: :galeria_ferramentas
  get 'galeria/Brinquedos', to: 'galeria#Brinquedos', as: :galeria_brinquedos
  get 'galeria/outros', to: 'galeria#Outros', as: :galeria_outros


  get 'browse', to: 'posts#browse', as: :browse_posts

  get 'home/index'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  post '/carrinho/create', to: 'carrinho#create', as: :create_carrinho
  post '/carrinho/:carrinho_id/car_comments', to: 'car_comments#create', as: :carrinho_car_comments
  delete '/carrinho/:carrinho_id/car_comments/:id', to: 'car_comments#destroy', as: :carrinho_car_comment
  get 'posts', to: 'posts#index', as: :posts
  get "/users/auth/facebook" => "callbacks#facebook", as: :facebook
  get 'profiles/show'
  resources :posts do
    collection do
      get :autocomplete
      get :autocomplete2
      get :autocompletepre
      get :autocompletepre2
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }
  root 'home#index'
  get '/search', to: 'home#search', as: :search
  get '/importar', to: 'posts#importar', as: :importar
  post '/importar/create', to: 'posts#importar_create', as: :importar_create

  get '/:user_name', to: 'profiles#show', as: :profile
  get '/:user_name/conta_bancaria', to: 'profiles#banco', as: :banco
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get ':user_name/printers', to: 'profiles#printers', as: :printers_profile
  get ':user_name/destaques', to:'profiles#destaques', as: :destaques_profile
  get ':user_name/projetos', to:'profiles#projetos', as: :projetos_profile
  get ':user_name/seguidores', to:'profiles#seguidores', as: :seguidores_profile
  get ':user_name/seguindo', to:'profiles#seguindo', as: :seguindo_profile
  get ':user_name/carrinho', to:'order#new', as: :carrinho
  get ':user_name/carrinhos', to:'carrinhos#index', as: :carrinhos
  get ':user_name/carrinho_feito/:id', to: 'carrinhos#show', as: :carrinho_feito
  post ':user_name/order/create', to:'order#create', as: :order_create
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  #post 'pedidos/create', to: 'pedidos#create', as: :pedidos
  post 'posts/:id/checkout', to: 'ckeckout#create', as: :checkout
  get 'posts/:id/new', to: 'ckeckout#new', as: :new_checkout
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout :determine_layout
  skip_before_action :verify_authenticity_token
  def index
    @contato = Contato.new
    @posts = Post.all.where.not(status: 0).order('cached_votes_up DESC').limit(9)
    @oferta = Ofert.new
  end

  def search
      @posts = Post.starts_with(params[:query]).where.not(status: 0).order('created_at DESC')
      @users = User.starts_with(params[:query]).order('created_at DESC')
      @query = params[:query]
  end
  def create
    @contato = Contato.create(contato_params)
    if @contato.save
      redirect_to root_path
    end
  end
  def create_oferta
    @oferta = Ofert.create(ofert_params)
    if @oferta.save
      redirect_to root_path
    end
  end
  def godaddy
  end

  private

  def contato_params
    params.require(:contato).permit(:name,:email,:mensagem)
  end
  def ofert_params
    params.require(:ofert).permit(:email)
  end
  def determine_layout
  		case action_name
  		when "index", "godaddy"
    		false
    	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_post.html.erb
    <% posts.each do |item| %>
	<div class="w3-container">
	
    	<div class="w3-card-2 w3-center">
    	<p class="w3-center">Nome do usuario</p>
      <%= link_to (image_tag item.image.url(:medium), class:"w3-hover-opacity img-responsive"), post_path(item) %>

	    <div class="w3-container w3-center w3-border-top">
	      <p>Descrição do post.</p>
	    </div>
	    </div>
	</div>
	<br>
    <% end %>


<style type="text/css">
	
	.imagem{
		width:25%;
		
	}
</style>

app/views/home/_projects.html.erb
    <% @posts.each do |post| %>
    <article class="white-panel", style='background-color:#f2f2f2'>
      <div class="img-box">
        <a href=<%=post_path(post)%>><div class="hover-mask2"></div></a>
        <span class="product-icon fa fa-print" style="display:inline;"></span>
        <%= link_to (image_tag post.image.url(:thumb)), post_path(post) %>
      <!--<div style="padding:10px 5px 0 5px">
        <span style='float:left; color:#009FAB'><p><b><%= post.caption %></b></p></span>
        <span style='float:right; color:#009FAB'><i class="fa fa-eye" aria-hidden="true"></i> <%=post.view%> <i class="fa fa-heart" aria-hidden="true"></i> <%=post.votes_for.up.by_type(User).size%> </li>
        </span>
        </div>-->
      </div>
        <div class="product-info col-md-12">
          <p class="project-price">R$<%=%></p>
          <div>
           <h4 class="project-title"><%=post.caption%></h4>
          </div>
        </div>
    </article>
    <% end %>

app/views/home/_user.html.erb
  <%users.in_groups_of(3, false).each do |group| %>
  <div class="w3-row-padding">
    <% group.each do |item| %>
    <div class="w3-third w3-container w3-margin-bottom">
      <%= link_to (image_tag item.avatar.url(:medium), class:"w3-hover-opacity", style:'width:100%'), profile_path(item.user_name) %>
      <div class="w3-container w3-white">
        <br>
        <p><b><%= item.completo %></b></p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>

app/views/home/godaddy.html.erb
rfhe306ut3ngnrihmfip31lpga

app/views/home/search.html.erb
<script src=<%= asset_path('pagination.js') %>></script>
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {font-weight:bold}
</style>
<style>

/*
Ref:
Thanks to:
https://www.jqueryscript.net/layout/Simple-jQuery-Plugin-To-Create-Pinterest-Style-Grid-Layout-Pinterest-Grid.html
*/

body {   
}    
.filtro-btn{
  background-color:#fff;
  color: black;
  cursor: pointer;
  border:none;
  border-radius: 5px;
  padding: 10px 18px;
}
.filtro-btn:hover {
  color: #009FAB;
}
.filtro-btn-azul{
  background-color:#009FAB;
  color:white;
  cursor: pointer;
  border:none;
  border-radius: 5px;
  padding: 10px 20px;
}
#pinBoot {
  position: relative;
  max-width: 100%;
  width: 100%;
}
.white-panel img {
  width: 100%;
  max-width: 100%;
}
.white-panel {
  position: absolute;
  background: white;
  border-radius: 5px;
}
/*
stylize any heading tags withing white-panel below
*/

.white-panel h1 {
  font-size: 1em;
}
.white-panel h1 a {
  color: #A92733;
}
</style>
<!--<script type="text/javascript" src="../assets/show_profile.js"></script>-->

<div class="w3-light-grey w3-content" style="max-width:1200px; padding-top: 30px">

<!-- Sidenav/menu -->

<!-- Overlay effect when opening sidenav on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
<!-- !PAGE CONTENT! -->
<div class="w3-main">

  <!-- Header -->
  <div class="w3-container" id="portfolio">
    <a href="#" onclick="w3_open()"></a>
    <span class="w3-opennav w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i style='padding-top: 40px' class="fa fa-bars"></i></span>
    <div class="w3-section w3-padding-16" style='border-bottom:4px solid #ccc'>
      <button class="w3-btn menuNat filtro-btn-azul" id="posts_search"><i class="fa fa-photo w3-margin-right"></i>Projetos <span style="color:red"><%=@posts.count%></span></button>
      <button class="w3-btn menuNat filtro-btn"" id="users_search" bla="#{galeria_path}"><i class="fa fa-user w3-margin-right"></i>Usuários <span style="color:red"><%=@users.count%></span></button>
    </div>
  </div>
  
<bla id="posts">


  <div id="my-posts">
  <% if @posts.any? %>
    <section id='pinBoot'>
      <%= render 'projects', posts: @posts %>
    </section>
  <% else %>
  <h2 class='w3-center'>Nao foram encontrados projetos para '<%=@query%>'
  <% end %> 
  </div>

  <!-- Pagination -->
  <!-- Footer -->
</bla>

<bla id="users" style='display: none'>
  <div id="my-users">
  <%if @users.any? %>
    <%= render 'user', users: @users %>
  <% else %>
    <h2 class='w3-center'>Nao foram encontrados usuários para '<%=@query%>'
  <% end %>
  </div>

  <!-- Pagination -->
  <!-- Footer -->
</bla>
<!-- End page content -->
</div>


<script>
// Script to open and close sidenav
function w3_open() {
    document.getElementById("mySidenav").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}


function w3_close() {
    document.getElementById("mySidenav").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}
</script>
<script>
$("#posts_search").click(function() {
  console.log("blaaaaaa");
  $('.w3-btn').addClass('filtro-btn');
  $('.w3-btn').removeClass('filtro-btn-azul');
  $(this).removeClass('filtro-btn');
  $(this).addClass('filtro-btn-azul');
  $("#users").hide();
  $("#posts").show();
});
$("#users_search").click(function() {
  $('.w3-btn').addClass('filtro-btn');
  $('.w3-btn').removeClass('filtro-btn-azul');
  $(this).removeClass('filtro-btn');
  $(this).addClass('filtro-btn-azul');
  console.log("blaaaaaa");
  $("#posts").hide();
  $("#users").show();
});
</script>
<script>
$(document).ready(function() {
$('#pinBoot').pinterest_grid({
no_columns: 4,
padding_x: 10,
padding_y: 10,
margin_bottom: 50,
single_column_breakpoint: 700
});
});

/*
Ref:
Thanks to:
https://www.jqueryscript.net/layout/Simple-jQuery-Plugin-To-Create-Pinterest-Style-Grid-Layout-Pinterest-Grid.html
*/


/*
    Pinterest Grid Plugin
    Copyright 2014 Mediademons
    @author smm 16/04/2014

    usage:

     $(document).ready(function() {

        $('#blog-landing').pinterest_grid({
            no_columns: 4
        });

    });


*/
;(function ($, window, document, undefined) {
    var pluginName = 'pinterest_grid',
        defaults = {
            padding_x: 10,
            padding_y: 10,
            no_columns: 3,
            margin_bottom: 50,
            single_column_breakpoint: 700
        },
        columns,
        $article,
        article_width;

    function Plugin(element, options) {
        this.element = element;
        this.options = $.extend({}, defaults, options) ;
        this._defaults = defaults;
        this._name = pluginName;
        this.init();
    }

    Plugin.prototype.init = function () {
        var self = this,
            resize_finish;

        $(window).resize(function() {
            clearTimeout(resize_finish);
            resize_finish = setTimeout( function () {
                self.make_layout_change(self);
            }, 11);
        });

        self.make_layout_change(self);

        setTimeout(function() {
            $(window).resize();
        }, 500);
    };

    Plugin.prototype.calculate = function (single_column_mode) {
        var self = this,
            tallest = 0,
            row = 0,
            $container = $(this.element),
            container_width = $container.width();
            $article = $(this.element).children();

        if(single_column_mode === true) {
            article_width = $container.width() - self.options.padding_x;
        } else {
            article_width = ($container.width() - self.options.padding_x * self.options.no_columns) / self.options.no_columns;
        }

        $article.each(function() {
            $(this).css('width', article_width);
        });

        columns = self.options.no_columns;

        $article.each(function(index) {
            var current_column,
                left_out = 0,
                top = 0,
                $this = $(this),
                prevAll = $this.prevAll(),
                tallest = 0;

            if(single_column_mode === false) {
                current_column = (index % columns);
            } else {
                current_column = 0;
            }

            for(var t = 0; t < columns; t++) {
                $this.removeClass('c'+t);
            }

            if(index % columns === 0) {
                row++;
            }

            $this.addClass('c' + current_column);
            $this.addClass('r' + row);

            prevAll.each(function(index) {
                if($(this).hasClass('c' + current_column)) {
                    top += $(this).outerHeight() + self.options.padding_y;
                }
            });

            if(single_column_mode === true) {
                left_out = 0;
            } else {
                left_out = (index % columns) * (article_width + self.options.padding_x);
            }

            $this.css({
                'left': left_out,
                'top' : top
            });
        });

        this.tallest($container);
        $(window).resize();
    };

    Plugin.prototype.tallest = function (_container) {
        var column_heights = [],
            largest = 0;

        for(var z = 0; z < columns; z++) {
            var temp_height = 0;
            _container.find('.c'+z).each(function() {
                temp_height += $(this).outerHeight();
            });
            column_heights[z] = temp_height;
        }

        largest = Math.max.apply(Math, column_heights);
        _container.css('height', largest + (this.options.padding_y + this.options.margin_bottom));
    };

    Plugin.prototype.make_layout_change = function (_self) {
        if($(window).width() < _self.options.single_column_breakpoint) {
            _self.calculate(true);
        } else {
            _self.calculate(false);
        }
    };

    $.fn[pluginName] = function (options) {
        return this.each(function () {
            if (!$.data(this, 'plugin_' + pluginName)) {
                $.data(this, 'plugin_' + pluginName,
                new Plugin(this, options));
            }
        });
    }

})(jQuery, window, document);
</script>

</div>